version: '3.3'

services:
  api:
    build: .
    image: ms-sample:latest
    ports:
      - "8080:8080"
    environment:
      - VERSION=${VERSION}
    tty: true
  db:
    image: mongo:latest
    command: mongod
    ports:
      - "27017:27017"
    volumes:
      - ./.tmp/mongo:/data/db
